In [34]:
import torch
import torch.nn as nn
import torch.nn.functional as F
class MyNeuralNet(nn.Module):
    def __init__(self, input_size, n_nodes, output_size):
        super(MyNeuralNet, self).__init__()
        self.operationOne = nn.Linear(input_size, n_nodes)
        self.operationTwo = nn.Linear(n_nodes, output_size)
    def forward(self, x):
        x = F.relu(self.operationOne(x))
        x = self.operationTwo(x)
        x = F.sigmoid(x)
        return x

In [35]:
my_network = MyNeuralNet(input_size = 3, n_nodes = 2, output_size = 1)

Understanding Tensors

In [36]:
import torch
first_order_tensor = torch.tensor([1, 2, 3])
print(first_order_tensor)

tensor([1, 2, 3])


In [37]:
print(first_order_tensor[0])

tensor(1)


In [38]:
print(first_order_tensor[0:2])

tensor([1, 2])


In [39]:
print(first_order_tensor[1:])

tensor([2, 3])


In [40]:
second_order_tensor = torch.tensor([ [ 11, 22, 33 ],
 [ 21, 22, 23 ]
 ])
print(second_order_tensor)

tensor([[11, 22, 33],
        [21, 22, 23]])


In [41]:
print(second_order_tensor[0, 1])

tensor(22)


In [42]:
fourth_order_tensor = torch.tensor(
[
 [
 [
 [1111, 1112],
 [1121, 1122]
 ],
 [
 [1211, 1212],
 [1221, 1222]
 ]
 ],
 [
 [
 [2111, 2112],
 [2121, 2122]
 ],
 [
 [2211, 2212],
 [2221, 2222]
 ]
 ]
])


In [43]:
my_tensor = torch.tensor([1, 2, 3, 4, 5])
print(my_tensor.size())

torch.Size([5])


In [44]:
my_tensor = torch.tensor([[11, 12, 13], [21, 22, 23]])
print(my_tensor.size())

torch.Size([2, 3])


In [45]:
print(fourth_order_tensor.size())

torch.Size([2, 2, 2, 2])


In [46]:
random_tensor = torch.rand([4, 2])
print(random_tensor)

tensor([[0.3855, 0.1029],
        [0.3011, 0.0792],
        [0.2385, 0.2531],
        [0.6522, 0.1399]])


In [47]:
random_tensor.view([2, 4])

tensor([[0.3855, 0.1029, 0.3011, 0.0792],
        [0.2385, 0.2531, 0.6522, 0.1399]])

In [48]:
random_tensor = torch.rand([4, 2, 4])
random_tensor.view([2, 4, -1])

tensor([[[0.7620, 0.6944, 0.7251, 0.0805],
         [0.7184, 0.2348, 0.7807, 0.7231],
         [0.0677, 0.3807, 0.2169, 0.9492],
         [0.3610, 0.7355, 0.2769, 0.8115]],

        [[0.6958, 0.6556, 0.7443, 0.8787],
         [0.7102, 0.0985, 0.1247, 0.0023],
         [0.9047, 0.3362, 0.0653, 0.9173],
         [0.2406, 0.2956, 0.1606, 0.2086]]])

In [49]:
random_tensor.view([2, -1, 4])

tensor([[[0.7620, 0.6944, 0.7251, 0.0805],
         [0.7184, 0.2348, 0.7807, 0.7231],
         [0.0677, 0.3807, 0.2169, 0.9492],
         [0.3610, 0.7355, 0.2769, 0.8115]],

        [[0.6958, 0.6556, 0.7443, 0.8787],
         [0.7102, 0.0985, 0.1247, 0.0023],
         [0.9047, 0.3362, 0.0653, 0.9173],
         [0.2406, 0.2956, 0.1606, 0.2086]]])

In [50]:
x = torch.tensor([5, 3])
y = torch.tensor([3, 2])
torch.add(x, y)

tensor([8, 5])

In [51]:
torch.sub(x, y)

tensor([2, 1])

In [52]:
torch.mul(x, y)

tensor([15,  6])

In [53]:
x + y

tensor([8, 5])

In [54]:
torch.div(x, y)

tensor([1.6667, 1.5000])

In [55]:
x.dtype

torch.int64

In [56]:
y.dtype

torch.int64

In [57]:
x_float = torch.tensor([5, 3], dtype = torch.float32)
y_float = torch.tensor([3, 2], dtype = torch.float32)
print(x_float / y_float)

tensor([1.6667, 1.5000])


In [58]:
torch.FloatTensor([5, 3])

tensor([5., 3.])

In [59]:
x.type(torch.DoubleTensor)

tensor([5., 3.], dtype=torch.float64)

# Importing our dataset as a PyTorch Tensor

In [60]:
import numpy as np
admit_data = np.genfromtxt('admit_status.csv', delimiter = ',', skip_header = 1)
print(admit_data)

[[  0.   380.     3.61   3.  ]
 [  1.   660.     3.67   3.  ]
 [  1.   800.     4.     1.  ]
 [  1.   640.     3.19   4.  ]
 [  0.   520.     2.93   4.  ]
 [  1.   760.     3.     2.  ]
 [  1.   560.     2.98   1.  ]
 [  0.   400.     3.08   2.  ]
 [  1.   540.     3.39   3.  ]]


In [61]:
admit_tensor = torch.from_numpy(admit_data)
print(admit_tensor)

tensor([[  0.0000, 380.0000,   3.6100,   3.0000],
        [  1.0000, 660.0000,   3.6700,   3.0000],
        [  1.0000, 800.0000,   4.0000,   1.0000],
        [  1.0000, 640.0000,   3.1900,   4.0000],
        [  0.0000, 520.0000,   2.9300,   4.0000],
        [  1.0000, 760.0000,   3.0000,   2.0000],
        [  1.0000, 560.0000,   2.9800,   1.0000],
        [  0.0000, 400.0000,   3.0800,   2.0000],
        [  1.0000, 540.0000,   3.3900,   3.0000]], dtype=torch.float64)


Training neural networks in PyTorch

In [62]:
x_train = admit_tensor[:6, 1:].float()
y_train = admit_tensor[:6, 0].float()
x_test = admit_tensor[6:, 1:].float()
y_test = admit_tensor[6:, 0].float()

In [63]:
x_train

tensor([[380.0000,   3.6100,   3.0000],
        [660.0000,   3.6700,   3.0000],
        [800.0000,   4.0000,   1.0000],
        [640.0000,   3.1900,   4.0000],
        [520.0000,   2.9300,   4.0000],
        [760.0000,   3.0000,   2.0000]])

In [ ]:
x_test

In [ ]:
criterion = nn.BCELoss()

In [64]:
x_test

tensor([[560.0000,   2.9800,   1.0000],
        [400.0000,   3.0800,   2.0000],
        [540.0000,   3.3900,   3.0000]])

In [65]:
criterion = nn.BCELoss()

In [66]:
x_test

tensor([[560.0000,   2.9800,   1.0000],
        [400.0000,   3.0800,   2.0000],
        [540.0000,   3.3900,   3.0000]])

In [67]:
criterion = nn.BCELoss()

In [68]:
optimizer = torch.optim.SGD(my_network.parameters(), lr=0.01)

In [69]:
for epoch in range(100):
    y_pred = torch.squeeze(my_network(x_train))
    loss_score = criterion(y_pred, y_train)
    print('epoch: ', epoch, 'loss: ', loss_score)
    
    optimizer.zero_grad()
    loss_score.backward()
    optimizer.step()

epoch:  0 loss:  tensor(33.3333, grad_fn=<BinaryCrossEntropyBackward>)
epoch:  1 loss:  tensor(33.3333, grad_fn=<BinaryCrossEntropyBackward>)
epoch:  2 loss:  tensor(33.3333, grad_fn=<BinaryCrossEntropyBackward>)
epoch:  3 loss:  tensor(33.3333, grad_fn=<BinaryCrossEntropyBackward>)
epoch:  4 loss:  tensor(33.3333, grad_fn=<BinaryCrossEntropyBackward>)
epoch:  5 loss:  tensor(33.3333, grad_fn=<BinaryCrossEntropyBackward>)
epoch:  6 loss:  tensor(33.3333, grad_fn=<BinaryCrossEntropyBackward>)
epoch:  7 loss:  tensor(33.3333, grad_fn=<BinaryCrossEntropyBackward>)
epoch:  8 loss:  tensor(33.3333, grad_fn=<BinaryCrossEntropyBackward>)
epoch:  9 loss:  tensor(33.3333, grad_fn=<BinaryCrossEntropyBackward>)
epoch:  10 loss:  tensor(33.3333, grad_fn=<BinaryCrossEntropyBackward>)
epoch:  11 loss:  tensor(33.3333, grad_fn=<BinaryCrossEntropyBackward>)
epoch:  12 loss:  tensor(33.3333, grad_fn=<BinaryCrossEntropyBackward>)
epoch:  13 loss:  tensor(33.3333, grad_fn=<BinaryCrossEntropyBackward>)
ep

/usr/local/lib/python3.8/dist-packages/torch/nn/functional.py:1639: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
/usr/local/lib/python3.8/dist-packages/torch/autograd/__init__.py:130: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.)
  Variable._execution_engine.run_backward(
