### Layers : Fundamental blocks of Neural Network

In [1]:
import torch
from torch.nn import Linear, ReLU
import torch.nn as nn
import numpy as np
from torch.autograd import Variable
from torchvision import models
from torchvision.datasets import ImageFolder

In [2]:
linear_layer = Linear(in_features=5,out_features=3,bias=True)

In [3]:
inp = Variable(torch.randn(1,5))
linear_layer(inp)

tensor([[-1.4803,  1.5296, -0.5879]], grad_fn=<AddmmBackward>)

In [4]:
linear_layer.weight

Parameter containing:
tensor([[ 0.3972, -0.2618,  0.3333,  0.0135, -0.1849],
        [ 0.4307,  0.0508, -0.3804, -0.4219,  0.2548],
        [ 0.2347, -0.4179, -0.1026, -0.2668, -0.4077]], requires_grad=True)

In [5]:
linear_layer.bias

Parameter containing:
tensor([-0.3136,  0.3921,  0.3318], requires_grad=True)

In [6]:
linear_layer = Linear(5,3)
linear_layer_2 = Linear(3,2)
linear_layer_2(linear_layer(inp))

tensor([[0.2692, 0.1608]], grad_fn=<AddmmBackward>)

In [7]:
myLayer = Linear(in_features=10,out_features=5,bias=True)
inp = Variable(torch.randn(1,10))
myLayer = Linear(in_features=10,out_features=5,bias=True) 
myLayer(inp)

tensor([[-0.4956, -0.1536,  0.2389,  0.3390,  0.1341]],
       grad_fn=<AddmmBackward>)

In [8]:
myLayer.weight

Parameter containing:
tensor([[-0.2265,  0.2239, -0.0015,  0.1009,  0.2926, -0.0115, -0.0517, -0.1060,
         -0.0801,  0.1963],
        [-0.3116,  0.1580,  0.1188,  0.2510, -0.1668, -0.1955, -0.0606,  0.3007,
          0.0140, -0.2983],
        [-0.0953,  0.2349, -0.2213,  0.0759,  0.0352,  0.0127, -0.2864,  0.1741,
          0.2894,  0.0964],
        [-0.0110,  0.2126,  0.1185, -0.2068, -0.0811, -0.1424,  0.2705, -0.2868,
          0.0797,  0.3154],
        [ 0.0191, -0.1379,  0.1251,  0.0807, -0.2323, -0.1153, -0.0909, -0.0158,
          0.1725, -0.1851]], requires_grad=True)

In [9]:
myLayer.bias

Parameter containing:
tensor([-0.1980,  0.1031, -0.1669,  0.2230,  0.1389], requires_grad=True)

### PyTorch Non-linear Activations

In [10]:
sample_data = Variable(torch.Tensor([[1,2,-1,-1]])) 
myRelu = ReLU()
myRelu(sample_data)

tensor([[1., 2., 0., 0.]])

In [11]:
import torch.nn as nn
import torch.nn.functional as F
sample_data = Variable(torch.Tensor([[1,2,-1,-1]])) 
f = F.relu(sample_data) # Much simpler.
f

tensor([[1., 2., 0., 0.]])

### Neural Network 

In [12]:
class MyFirstNetwork(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(MyFirstNetwork,self).__init__() 
        self.layer1 = nn.Linear(input_size,hidden_size) 
        self.layer2 = nn.Linear(hidden_size,output_size)
    def __forward__(self,input): 
        out = self.layer1(input) 
        out = nn.ReLU(out)
        out = self.layer2(out) 
        return out

In [13]:
my_network = MyFirstNetwork(input_size = 3, hidden_size = 2, output_size = 1)

### Loss

In [14]:
loss = nn.MSELoss()
input = Variable(torch.randn(3, 5), requires_grad=True) 
target = Variable(torch.randn(3, 5))
output = loss(input, target)
output.backward()

/usr/local/lib/python3.8/dist-packages/torch/autograd/__init__.py:130: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.)
  Variable._execution_engine.run_backward(


In [15]:
def cross_entropy(true_label, prediction):
    if true_label == 1:
        return -log(prediction)
    else:
        return -log(1 - prediction)

In [16]:
loss = nn.CrossEntropyLoss()
input = Variable(torch.randn(3, 5), requires_grad=True) 
target = Variable(torch.LongTensor(3).random_(5)) 
output = loss(input, target)
output.backward()

### Optimizer

In [17]:
# for demo
optimizer = torch.optim.SGD(my_network.parameters(), lr = 0.01)
for input, target in torch.utils.data.Dataset:
    optimizer.zero_grad()
    output = model(input)
    loss = loss_fn(output, target)
    loss.backward()
    optimizer.step()

TypeError: 'type' object is not iterable